---
output: 
    html_document:
        theme: flatly
runtime: shiny_prerendered
---

```{r setup, context = "setup", include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = F, message = F, 
                      fig.asp = 0.621, out.width = "100%", fig.width = 8)

library(tidyverse); library(knitr); library(kableExtra); 
library(broom); library(cowplot); 
library(rstan); library(tidybayes); library(scales); library(lubridate)

theme_set(theme_classic(base_size = 12) + 
            background_grid(color.major = "grey90", 
                            color.minor = "grey95", 
                            minor = "xy", major = "xy") +
            theme(legend.position = "none"))

```

```{r, context = "data"}
d <- read_csv("../../Data/COVID_Data_2020-07-28.csv")

plot_d <- read_csv("../../Data/COVID_Data_2020-07-28.csv")

m <- read_rds("../../Models/Model_2020-07-28.rds")
res <- spread_draws(m, 
                    alpha[location],
                    beta[location], 
                    S[location],
                    phi[location],
                    nu[location],
                    n = 2000) %>% 
  ungroup
```


```{r, context = "render", fig.asp = 1}
fluidRow(
  column(2,
         actionButton(inputId = "gobutton", label = "Predict")
  ),
  column(2,
         selectInput(inputId = "location",
                     label = "Location",
                     choices = unique(d$location), selected = "Iceland")
  ),
  column(2,
         selectInput(inputId = "scale",
                     label = "Scale", choices = c("Additive", "Log", "Logit"), selected = "Additive")
  ),
  column(3,
         dateInput(inputId = "date",
                   label = "Pred date", 
                   min = Sys.Date(), max = Sys.Date() + months(12), 
                   value = Sys.Date() + months(1), weekstart = 1, startview = "year")
  ),
  column(2,
         selectInput(inputId = "pred_type",
                     label = "Pred type", 
                     choices = c("Start", "Current"), 
                     selected = "start")
  )
)

plotOutput("pred_plot", height = "800px")
```

```{r, context = "server"}
pred_plot <-  eventReactive(input$gobutton, {
  
  plot_dat <- plot_d %>% filter(location == input$location)
  info_dat <- d %>% filter(location == input$location)
  id <- unique(info_dat$location_id)
  pop <- unique(info_dat$population)
  start_cases <- ifelse(input$pred_type == "Start",
                        min(info_dat$total_cases),
                        max(info_dat$total_cases))
  
  start_date <- min(info_dat$date)
  end_date <- max(info_dat$date)
  
  alph <- 0.05
  
  days_in_data <- max(info_dat$days) + 1
  
  if (input$pred_type == "Start") {
    day_seq <- seq(0, as.numeric(input$date - start_date), by = 1)
  } else {
    day_seq <- seq(days_in_data, days_in_data + as.numeric(input$date - end_date), by = 1)
  }
  
  if (input$scale != "Logit") {
    results <-  res %>% 
      filter(location == id) %>% 
      mutate(iter = row_number()) %>% 
      select(iter, alpha, beta, S, phi, nu) %>% 
      expand_grid(days = day_seq) %>% 
      mutate(z = beta * (days - alpha),
             f = S - S / (1 + nu * exp(z))^(1/nu),
             dfdt = beta * (S - f) * (1 - ((S - f) / S)^nu) / nu,
             daily_cases = rnbinom(n(), mu = dfdt * pop, size = phi)) %>% 
      group_by(iter) %>% 
      mutate(cases = as.numeric(cumsum(daily_cases * (days > 0))) + start_cases) %>% 
      ungroup %>% 
      select(iter, days, new_cases = daily_cases, cumulative_cases = cases)
    
    
    if (input$pred_type == "Start") {
      day_seq <- seq(0, as.numeric(input$date - start_date), by = 1)
    } else {
      day_seq <- seq(days_in_data, days_in_data + as.numeric(input$date - end_date), by = 1)
    }
    
    
    plot_lab1 <- str_c("New cases in  ", 
                       input$location, 
                       ": Prediction and observations")
    
    p1 <- results %>% 
      mutate(date = days + min(plot_dat$date)) %>% 
      filter(days > 0) %>% 
      group_by(date) %>% 
      summarise(median = median(new_cases),
                lower = quantile(new_cases, alph / 2),
                upper = quantile(new_cases, 1 - alph / 2)) %>% 
      ggplot(aes(date, median, ymin = lower, ymax = upper)) +
      geom_line(aes(y = lower), lty = 2) +
      geom_line(aes(y = upper), lty = 2) +
      geom_line() +
      geom_point(data = plot_dat,
                 aes(date, new_cases), inherit.aes = F) +
      # geom_point(data = plot_dat,
      #            aes(date, rolling_new_cases), inherit.aes = F, col = "grey60") +
      scale_y_continuous(breaks = pretty_breaks(8)) +
      labs(y = "Count",
           title = plot_lab1,
           subtitle = "Predicted median and PI") +
      theme(axis.title.x = element_blank(), plot.margin = margin(5, 5, 5, 8.5))
    
    plot_lab2 <- str_c("Cumulative cases in  ", 
                       input$location, 
                       ": Prediction and observations")
    
    p2 <- results %>% 
      mutate(date = days + min(plot_dat$date)) %>% 
      filter(days > 0) %>% 
      group_by(date) %>% 
      summarise(median = median(cumulative_cases),
                lower = quantile(cumulative_cases, alph / 2),
                upper = quantile(cumulative_cases, 1 - alph / 2)) %>% 
      ggplot(aes(date, median, ymin = lower, ymax = upper)) +
      geom_line(aes(y = lower), lty = 2) +
      geom_line(aes(y = upper), lty = 2) +
      geom_line() +
      geom_point(data = plot_dat,
                 aes(date, total_cases), inherit.aes = F) +
      scale_y_continuous(breaks = pretty_breaks(8)) +
      labs(y = "Count",
           title = plot_lab2,
           subtitle = "Predicted median and PI") +
      theme(axis.title.x = element_blank())
    
    p3 <- results %>% 
      mutate(date = days + min(plot_dat$date)) %>% 
      filter(days > 0) %>% 
      filter(iter %in% sample(iter, size = 200)) %>% 
      ggplot(aes(date, cumulative_cases, group = iter)) +
      geom_line(alpha = 0.1) +
      geom_point(data = plot_dat, col = "grey", size = 2,
                 aes(date, total_cases), inherit.aes = F) +
      scale_y_continuous(breaks = pretty_breaks(8)) +
      labs(y = "Count",
           subtitle = "Possible growth curves drawn from posterior distribution") +
      theme(axis.title.x = element_blank())
    
    
    if (input$scale == "Log") {
      p1 <- p1 + scale_y_log10(breaks = c(1, 3, 10, 30, 100, 300, 1000, 3000,
                                          10000, 30000, 100000, 300000, 1000000, 3000000))
      p2 <- p2 + scale_y_log10(breaks = c(1, 3, 10, 30, 100, 300, 1000, 3000,
                                          10000, 30000, 100000, 300000, 1000000, 3000000))
      
      p3 <- p3 + scale_y_log10(breaks = c(1, 3, 10, 30, 100, 300, 1000, 3000,
                                          10000, 30000, 100000, 300000, 1000000, 3000000))
    }
    
    
    plot_grid(p1, p2, p3, nrow = 4)
  } else {
    res %>% 
      filter(location == id) %>% 
      mutate(iter = row_number()) %>% 
      select(iter, alpha, beta, S, phi, nu) %>% 
      expand_grid(plot_dat) %>% 
      mutate(perc = total_cases / population,
             logit_y = log(perc / (S - perc))) %>% 
      select(perc, S, logit_y)
  }
  
})

output$pred_plot <- renderPlot({
  pred_plot()
})
```
